17.17

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -56,12 +56,6 @@ jobs:
       - name: Load Docker Image
         run: docker load --input bookclub-api-image.tar
 
-      - name: Clean up Docker environment
-        run: |
-          docker ps -q | xargs -r docker stop
-          docker ps -a -q | xargs -r docker rm
-          docker network prune -f || true
-
       - name: Start Docker Compose
         run: docker-compose up -d
 
@@ -106,12 +100,6 @@ jobs:
       - name: Load Docker Image
         run: docker load --input bookclub-api-image.tar
 
-      - name: Clean up Docker environment
-        run: |
-          docker ps -q | xargs -r docker stop
-          docker ps -a -q | xargs -r docker rm
-          docker network prune -f || true
-
       - name: Start Docker Compose
         run: docker-compose up -d
 
@@ -121,11 +109,18 @@ jobs:
             echo "query.txt not found" && exit 1
           else
             echo "query.txt found"
+            cat query.txt
           fi
 
       - name: Read and execute queries
         run: |
           while read -r query; do
+            echo "Executing query: ${query}"
+            response=$(curl -s -w "%{http_code}" -o /dev/null "http://localhost:5001/books${query}")
+            if [ "$response" -ne 200 ]; then
+              echo "Error: Failed to execute query ${query}. HTTP status code: $response"
+              exit 1
+            fi
             response=$(curl -s "http://localhost:5001/books${query}")
             echo -e "query: ${query}\nresponse: ${response}\n" >> response.txt
           done < query.txt
